### PR TITLE
2020 release candidate

### LINKED ISSUE #157: Missing sense keys (dc.identifier)
In english-wordnet-2019.xml as well as in the lexicographic src directory, 1077 lemmas do not have a sense key (dc.identifier). 
Mostly, these correspond to the additions made in this WordNet version, and are very probably the reason for 681 missing sense keys in the index.sense file, and may also explain the 28 overloaded lex_ids in the Princeton-compatible data files.

### LINKED ISSUE #249: Merge synsets from enWordNet (plWordNet)
This issue is to track the merging of enWordNet synsets into this resource.

The list of synsets can be viewed in this document:

https://docs.google.com/spreadsheets/d/1bTTF6mc5SVMVjyXdxhDS27zOQp43vbJCvUvL639F4Oo/edit#gid=0

### LINKED ISSUE #250: Merge synsets from Colloquial WordNet
Tracking issue for merging and checking Colloquial WordNet. Will be formed into a pull request soon.

### LINKED ISSUE #251: Provide sense and lemma ordering for new synsets from Colloquial
Tracking issue contributing to #250 

The following lemmas from Colloquial WordNet should be ordered relative to existing elements

android
bump
geek
hoe
jailbreak
lack
slay
brick
woosh
ball
bench
binge
bulk
catfish
chargeable
cringe
cuff
dab
dab
dank
falsie
favorite
fix
follow
fuck
glitch
hate
lurk
mug
pop-up
post
post
malware
sext
slap
squat
stress
stunt
swat
text
thug
trap
trend
tweak
tweet
tweet
unbox
vibe
whelm
woosh

The following new synsets should have their lemmas ordered:

['ewn-91000711-n', 'ewn-91000431-n', 'ewn-900001012-n', 'ewn-900008291-n', 'ewn-900018571-n', 'ewn-900014161-n']

### PR DESCRIPTION
**Pull request by jmccrae**
This branch represents the release candidate for the 2020 edition of English WordNet

Closes #371 
Closes #251 
Closes #250 
Closes #249
Closes #309 
Closes #408 
Closes #298
Fix #157

### CODE REVIEW

**Comment by 1313ou** [comment]
N O   S E N S E
Although allowed by DTD, does it make sense to have a lexical item that is not a member of any synset and _thus not part of the word net_ ?

```
XML: src/wn-adj.all.xml
[E] uncompleted content model. expecting: <Form>,<Sense> [row,col,system-id]: [28506,5,"file:src/wn-adj.all.xml"]
    <LexicalEntry id="ewn-sectarian-a">
      <Lemma writtenForm="sectarian" partOfSpeech="a"/>
no sense
    </LexicalEntry>

XML: src/wn-noun.location.xml
[E] uncompleted content model. expecting: <Form>,<Sense> [row,col,system-id]: [10148,5,"file:src/wn-noun.location.xml"]
    <LexicalEntry id="ewn-Black_Hills-n">
      <Lemma writtenForm="Black Hills" partOfSpeech="n"/>
no sense
    </LexicalEntry>

```
M U L T I P L E   D E F I N I T I O N S
Although allowed by schema (what's the point?), it hardly makes any sense to maintain multiple redundant definitions
```
XML: src/wn-adj.pert.xml
[E] tag name "Definition" is not allowed. Possible tag names are: <Example>,<ILIDefinition>,<SynsetRelation> [row,col,system-id]: [37402,7,"file:src/wn-adj.pert.xml"]
    <Synset id="ewn-02801550-a" ili="i15789" partOfSpeech="a" dc:subject="adj.pert">
      <Definition>of or relating to the countryside as opposed to the city</Definition>
      <Definition>living in or characteristic of farming or country life</Definition>

XML: src/wn-adv.all.xml
[E] tag name "Definition" is not allowed. Possible tag names are: <Example>,<ILIDefinition>,<SynsetRelation> [row,col,system-id]: [45210,7,"file:src/wn-adv.all.xml"]
      <Definition>quickly and without warning</Definition>
      <Definition>happening unexpectedly</Definition>
      <Definition>on impulse; without premeditation</Definition>

XML: src/wn-noun.food.xml
[E] tag name "Definition" is not allowed. Possible tag names are: <Example>,<ILIDefinition>,<SynsetRelation> [row,col,system-id]: [23134,7,"file:src/wn-noun.food.xml"]
      <Definition>food from the seed of the mung bean plant</Definition>
      <Definition>seed of the mung bean plant used for food</Definition>

XML: src/wn-noun.plant.xml
[E] tag name "Definition" is not allowed. Possible tag names are: <Example>,<ILIDefinition>,<SynsetRelation> [row,col,system-id]: [108929,7,"file:src/wn-noun.plant.xml"]
      <Definition>seed of the mung bean plant</Definition>
      <Definition>seed of the mung bean plant; used for food</Definition>

```

**Comment by 1313ou** [comment]
```
[E] Undefined ID 'ewn-extinguish-v-01213186-03': referenced from element <SyntacticBehaviour>, attribute 'senses' [row,col,system-id]: [1185,7,"file:src/wn-verb.change.xml"]
X
      <SyntacticBehaviour subcategorizationFrame="Somebody ----s something" senses="ewn-extinguish-v-00472642-01 ewn-extinguish-v-00479148-02 ewn-extinguish-v-01213186-03"/>

```

**Comment by 1313ou** [comment]
N O  S E N S E  (2)

```
[E] tag name "SyntacticBehaviour" is not allowed. Possible tag names are: <Form>,<Sense> [row,col,system-id]: [19778,7,"file:19778gsrc/wn-verb.change.xml"]
   <LexicalEntry id="ewn-press_out-v">
      <Lemma writtenForm="press out" partOfSpeech="v"/>
no sense
      <SyntacticBehaviour subcategorizationFrame="Somebody ----s something" senses="ewn-press_out-v-01213186-06"/>
    </LexicalEntry>

```

**Comment by 1313ou** [comment]
You didn't want to remove the lexical entries with these written forms but they are cryptic garbage (google for them - between "")

'3-[2-(Dimethylamino)ethyl]-4-indolol'
'4-Methyl-1-(1-methylethyl)-1,4-cyclohexadiene'
'4-Methyl-1-(1-methylethyl)-1,3-cyclohexadiene'
'4-Methylene-1-(1-methylethyl)cyclohexene'

**Comment by 1313ou** [comment]
S I M I L A R
Instances of 'similar' among nouns have been converted to 'see_also' except these originating from Colloq.
The first relation crosses POS lines ( a noun is similar to a verb)

```
Illegal=pos=n relType=similar id=ewn-00627814-n offset=0
--------------------------------------------------------
<Synset id="ewn-00627814-n"
              ili="i38715"
              partOfSpeech="n"
              dc:subject="noun.act"
              lexicalized="true">
         <Definition>a weightlift in which you lie on your back on a bench and press weights upward</Definition>
         <SynsetRelation relType="hypernym" target="ewn-00627428-n"/>  <!-- weightlift, weightlifting -->
         <SynsetRelation relType="hyponym" target="ewn-00627968-n"/>   <!-- incline bench press -->
         <SynsetRelation relType="similar" target="ewn-91000211-v"/>
         <SynsetRelation relType="similar" target="ewn-91000201-v"/>
      </Synset>

<Synset id="ewn-91000201-v"
              ili="in"
              partOfSpeech="v"
              dc:subject="noun.act"
              dc:source="Colloquial WordNet"
              lexicalized="true">
         <Definition>To exercise using a bench press</Definition>
         <SynsetRelation relType="hypernym" target="ewn-00627428-n"/>
         <!-- weightlift, weightlifting -->
         <SynsetRelation relType="similar" target="ewn-00627814-n"/>
         <!-- bench press -->
      </Synset>

<Synset id="ewn-91000211-v"
              ili="in"
              partOfSpeech="v"
              dc:subject="noun.act"
              dc:source="Colloquial WordNet"
              lexicalized="true">
         <Definition>To lift a weight using a bench press</Definition>
         <SynsetRelation relType="hypernym" target="ewn-00627428-n"/>
         <!-- weightlift, weightlifting -->
         <SynsetRelation relType="similar" target="ewn-00627814-n"/>
         <!-- bench press -->
      </Synset>

Illegal=pos=n relType=similar id=ewn-00856798-n offset=0
--------------------------------------------------------
<Synset id="ewn-00856798-n"
              ili="i39890"
              partOfSpeech="n"
              dc:subject="noun.act"
              lexicalized="true">
         <Definition>oral stimulation of the penis</Definition>
         <SynsetRelation relType="hypernym" target="ewn-00856505-n"/>
         <!-- head, oral sex -->
         <SynsetRelation relType="hyponym" target="ewn-00856930-n"/>
         <!-- cock sucking, blowjob -->
         <SynsetRelation relType="similar" target="ewn-90001611-n"/>
      </Synset>

<Synset id="ewn-90001611-n"
              ili="in"
              partOfSpeech="n"
              dc:subject="noun.act"
              dc:source="Colloquial WordNet"
              lexicalized="true">
         <Definition>A sexual activity where fellatio is performed on multiple men</Definition>
         <SynsetRelation relType="hypernym" target="ewn-00845915-n"/>
         <!-- sex, sex activity, sexual practice, sexual activity -->
         <SynsetRelation relType="similar" target="ewn-00856798-n"/>
         <!-- fellatio, fellation -->
      </Synset>


Illegal=pos=n relType=similar id=ewn-06253100-n offset=0
--------------------------------------------------------
<Synset id="ewn-06253100-n"
              ili="i69317"
              partOfSpeech="n"
              dc:subject="noun.cognition"
              lexicalized="true">
         <Definition>the ultimate principle of the universe</Definition>
         <SynsetRelation relType="hypernym" target="ewn-05881099-n"/>
         <!-- principle -->
         <SynsetRelation relType="holo_part" target="ewn-05986207-n"/>
         <!-- Daoism, Taoism -->
         <SynsetRelation relType="domain_topic" target="ewn-05986207-n"/>
         <!-- Daoism, Taoism -->
         <SynsetRelation relType="similar" target="ewn-89312075-n"/>
      </Synset>
<Synset id="ewn-89312075-n"
              ili="in"
              partOfSpeech="n"
              dc:subject="noun.cognition"
              lexicalized="true">
         <Definition>basic principles of the cosmos in Hinduism, Buddhism, Sikhism, Jainism and other religions</Definition>
         <SynsetRelation relType="hypernym" target="ewn-05881099-n"/>
         <!-- principle -->
         <SynsetRelation relType="similar" target="ewn-06253100-n"/>
         <!-- Tao -->
      </Synset>

Illegal=pos=n relType=similar id=ewn-06380437-n offset=0
--------------------------------------------------------
<Synset id="ewn-06380437-n"
              ili="i69944"
              partOfSpeech="n"
              dc:subject="noun.communication"
              lexicalized="true">
         <Definition>a genre of fast-paced science fiction involving oppressive futuristic computerized societies</Definition>
         <SynsetRelation relType="hypernym" target="ewn-06380251-n"/>
         <!-- science fiction -->
         <SynsetRelation relType="similar" target="ewn-91001481-n"/>
      </Synset>
<Synset id="ewn-91001481-n"
              ili="in"
              partOfSpeech="n"
              dc:subject="noun.communication"
              dc:source="Colloquial WordNet"
              lexicalized="true">
         <Definition>A subgenre of speculative science fiction set in an anachronistic 19th century society.</Definition>
         <SynsetRelation relType="hypernym" target="ewn-07106786-n"/>
         <!-- genre, writing style, literary genre -->
         <SynsetRelation relType="similar" target="ewn-06380437-n"/>
         <!-- cyberpunk -->
         <SynsetRelation relType="hypernym" target="ewn-10512479-n"/>
      </Synset>

```

**Comment by jmccrae** [comment]
Thanks. I will improve the validation #412 and #413 are issues related to your reports.

I can remove the chemical name entries. They don't really fit into the idea of WordNet as a general-domain language resource.

For multiple definitions, the reason for this is that entries have been merged and both definitions were considered valid. As there are other resources that use the definitions, especially the sense-tagged corpus that is part of the Princeton release and @arademaker is extending, we want to keep definitions. As such, if there are two definitions that could be sense-tagged both are listed in the merged entry. You can interpret the first one as the main definition and the web interface/WNDB export will only give the first definition.

**Comment by 1313ou** [comment]
> we want to keep definitions.
So be it. But it does not sound like a work in progress (there are 5 multiply-defined synsets only). My opinion is that when there are so few occurrences it must be an error.

**Comment by jmccrae** [comment]
Okay, #419 is created.

**Pull request merged**
