### PR TITLE
Collocations

### PR DESCRIPTION
**Pull request by 1313ou**
OEWN lacks collocation relations, i.e. relations of words+meanings on the 
syntagmatic axis. These were sometimes hinted at in the examples.

This PR brings collocations to OEWN as **sense relations** 
(a relation between two words, each within a semantic context 
expressed by a synset)

The collocations here are provided by SyntagNet, a **manually-curated** large-scale lexical-semantic 
combination database which associates pairs of concepts with pairs of co-occurring words, 
hence capturing sense distinctions evoked by syntagmatic relations.

SyntagNet is licensed under the CC BY-NC-SA 4.0 License.

Authors are Marco Maru, Federico Scozzafava, Federico Martelli and Roberto Navigli (Sapienza Università di Roma and Babelscape). This project is funded by the MOUSSE ERC and the[ ELEXIS ](https://elex.is/) project under the European Union's Horizon 2020 research and innovation programme.

Paper: [SyntagNet: Challenging Supervised Word Sense Disambiguation with Lexical-Semantic Combinations](https://aclanthology.org/D19-1359.pdf)

[Site](http://syntagnet.org)

[About](http://syntagnet.org/about)

[Download SyntagNet](http://syntagnet.org/download)

174768 collocations were added (87384+87384 both ways)

616 failed due to 239 senses being obsoleted or some flawed symmetrical source data.

### CODE REVIEW

**Comment by 1313ou** [comment]
There's something wrong with the PR-submission verification process.

_xmllint --noout --valid wn.xml_ fails because it checks new data (new relation) against old standards (DTD)

**Any proposal in this direction is bound to fail.**

otherwise from_yaml.py and validate.py are ok

**Comment by fcbond** [comment]
Hi,

It is a great idea, but isn't the license incompatible?   Adding this data would mean we need to change our license to  CC BY-NC-SA 4.0, as it is a share-alike license.  

I am afraid BableNet data is generally unusable.

**Comment by 1313ou** [comment]
_xmllint --noout --dtdvalid WN-LMF-1.4.dtd wn.xml_ succeeds 
with WN-LMF-1.4.dtd being the sames as WN-LMF-1.3.dtd but for the addition of 'collocation' to the sense relation type enumeration

**Comment by jmccrae** [comment]
I have a few issues with this:

1) As @fcbond points out, the license is incompatible with our resource. We would have to ask the Sapienza NLP team to change the license to allow us to include this data.
2) We have no real way to establish the quality of the links generated. My experience with resources coming from the Sapienza NLP group is that they are good for NLP but they are not generally at the high quality level of lexicographic resources. A quick browse through SyntagNet confirms for me that there are many collocations there that seem to have questionable sense disambiguation.
3) Collocations are difficult to define. A collocation is [a series of words or terms that co-occur more often than would be expected by chance](https://en.wikipedia.org/wiki/Collocation), but a key question is how much more than chance do they need to occur? Defining an appropriate metric and threshold is a challenge here that does not have an obvious answer. 
4) Collocations can be easily extracted directly from a sense-tagged corpus, according to a user's specific methodology. They are not lexical facts like hypernymy that we would normally include in WordNet. Although, of course many lexicographic resources do contain collocations, so it is possible to do this.

This is just my opinion and it is up to the community to see if this is a direction we want to take with the resource.

**Comment by 1313ou** [comment]
I've thought better of it.

Nobody wants OEWN to grow fatter, so 'thinner' and 'modular' are the words: I've always preferred (and worked on) interconnections rather than incorporation.

However the mechanism for extension must be provided for, so I have added a PR in the globalwordnet/schema project and this one, with data additon reverted, just to support the idea of collocations expressed as sense relations. One is then free to use it or leave it.

I have provided 
- the data [syntagnet for oewn](https://github.com/x-englishwordnet/syntagnet)
- the [model-injector + yaml-augmenter](https://github.com/oewntk/oewn-core) in the form of an extra module **oewn_syntagnet** in the oewn_core lib

Both implement the extension.

Better _inject_ than _ingest_.

**Comment by jmccrae** [comment]
I think that having these as external resources would be the best solution.

Perhaps links can be added to the `TOOLS.md` file to indicate them as useful external projects that are useful?

**Pull request closed without merging**
