### PR TITLE
Change gendered use of pronouns in definitions

### LINKED ISSUE #1058: Gender-biased use of pronouns in definitions
There are a lot of definitions that use the male pronoun in a way that implies gender, when the term is not gendered. For example

> a contract in which the contractor is paid **his** total cost plus a stated percentage of profit ([06534775-n](https://en-word.net/lemma/cost-plus%20contract))

Which could be changed to 

> a contract in which the contractor is paid **her or his** total cost plus a stated percentage of profit

A complete list of changes has been collected here. This affects the definition of 189 synsets

https://docs.google.com/spreadsheets/d/1BnQttTXLDFUeeDwtrkIh2WM63n0teDRpYCI6oivZ5HI/edit?usp=sharing

In a few borderline cases, where it is not clear if gender is assumed we will instead rewrite to avoid the use of pronouns

> belief of the Roman Catholic Church that God protects the pope from error when he speaks about faith or morality ([04812863-n](https://en-word.net/lemma/papal%20infallibility))

to 

> belief of the Roman Catholic Church that God protects the pope from error when **the pope** speaks about faith or morality

### PR DESCRIPTION
**Pull request by jmccrae**
This changes all uses of generic 'he' in definitions to generic 'they'

Fixes #1058

### CODE REVIEW

**Comment by 1313ou** [comment]
06572930-n should be:
`no contest´

**Comment by fcbond** [comment]
Overall these look good.

**Comment by goodmami** [comment]
@jmccrae Sorry I didn't see this MR before it was merged. Several instances of *they* have improper syntactic agreement (*they throws*, *they is*, *they seeks*, ...). I think this should only occur for *they* and not *them*, *their*, etc.

**Comment by jmccrae** [comment]
Changes in #1106

**Pull request merged**
