### PR TITLE
Add removed vulgar synsets from WordNet 3.0

### LINKED ISSUE #151: Inclusion of slurs?
Princeton WordNet 3.0 contains many racial, homophobic and other slurs that are no longer in 3.1 and hence not in this wordnet. Does the community feel that it would be a good idea to include these words again?

The complete list is:
* abo
* african_american
* afro-american
* amerindian_race
* black_american
* blackamoor
* black_man
* black_person
* black_race
* black_woman
* caucasian_race
* caucasoid_race
* colored
* colored_person
* darkey
* darkie
* darky
* gay_man
* jigaboo
* mayas
* mongolian_race
* mongoloid_race
* negress
* negroid_race
* negro_race
* nigga
* nigger
* nigra
* oriental
* oriental_person
* paleface
* people_of_color
* people_of_colour
* red_indian
* shirtlifter
* slant-eye
* white_people
* white_race
* yellow_man
* yellow_race
* yellow_woman

### PR DESCRIPTION
**Pull request by jmccrae**
Warning these are some fairly offensive terms!

Fixes #151

### CODE REVIEW

**Comment by jmccrae** [comment]
Working branch is here:
https://github.com/globalwordnet/english-wordnet/tree/issue-151-working

**Comment by arademaker** [comment]
I don't see reasons for adding these terms here.

**Comment by jmccrae** [comment]
The reason is that they are part of the English language, so fall within the scope of this project.

**Comment by arademaker** [comment]
I disagree, but with only two votes will be hard to get real consensus.

**Comment by jmccrae** [comment]
Seems to be 2-1 to me, but pushing to 2021 as there is disagreement :)

**Comment by 1313ou** [comment]
I'm for inclusion. Any historian should be able to quote Hitler without endorsing what he said.

**Comment by 1313ou** [comment]
Howewer "offensive term for" should appear in the definition
and
a SynsetRelation relType="exemplifies" (derogation, disparagement, depreciation)
or/and relType="exemplifies" (racism)
or/and a SynsetRelation relType="exemplifies" (white supremacy)
should be systematic

**Comment by fcbond** [comment]
I also think these should be added, so long as they are appropriately marked (which should happen with #554).

Ideally the online interface should show all the **domain** and **exemplifies** tags, so users are aware of their status.

**Pull request closed without merging**
