### PR TITLE
misc corrections, mostly typos

### PR DESCRIPTION
**Pull request by cmbant**
This was auto-generated, I have made some manual checks but you may want to do more.

### CODE REVIEW

**Comment by arademaker** [comment]
Do we have some statistics about these changes? How many glosses are changed? What changes are made?

**Comment by arademaker** [comment]
BTW, I would vote to make all PR linked to an issue, so we could better track the changes and its rationality.

**Comment by jmccrae** [comment]
I manually checked all of these and did a few modifications. They are mostly minor errors, although there were a few issues that I reverted, e.g., the pull request introduces a few &nbsp; characters and there is one change that was incorrect ("Liberal Democrat[ic] Party")

**Comment by arademaker** [comment]
hi @jmccrae , I notice the change below that is not trivial

```xml
     <Synset id="ewn-08932200-n" ili="i83573" partOfSpeech="n" dc:subject="noun.location">
-      <Definition>an ancient city in northwestern Iran; known for hot springs</Definition>
+      <Definition>an ancient city in northwestern Iran</Definition>
       <SynsetRelation relType="instance_hypernym" target="ewn-08542298-n"/> <!-- urban center, metropolis, city -->
       <SynsetRelation relType="holo_part" target="ewn-08930441-n"/> <!-- Islamic Republic of Iran, Iran, Persia -->
     </Synset>
````

**Comment by jmccrae** [comment]
True, but it also seems to be barely mentioned on the Wikipedia page for the city https://en.wikipedia.org/wiki/Tabriz so I believe that the change is for the better

**Comment by arademaker** [comment]
I would vote on monotonic changes only on the glosses, except for errors.

**Pull request merged**
