### PR TITLE
Added one simple typo patch.

### PR DESCRIPTION
**Pull request by daikinomura**
I would like to make a pull request every weekend with our newly found patches.

### CODE REVIEW

**Comment by arademaker** [comment]
Hi @jmccrae , is it ok to accept this PR? Can we help on that?

**Comment by fcbond** [comment]
I think commenting that you have read and think it is ok is good.   I think we are still trying to establish the criteria for oking the requests ---
 

- anyone can OK them?
- only Christiane can OK them?
- anyone can OK them after one more person has OKed them (so each patch has three peoples input - submiter, reviewer, merger)?   This can be enforced by github: https://help.github.com/articles/about-required-reviews-for-pull-requests/

FWIW, I am ok with this patch, thanks Daiki, I will try to formally review it.

**Comment by daikinomura** [comment]
Hi Alexandre.

I thought I lost some of my comments as I viewed it with my gitk.
Your links told me where it goes. I would like to take care next time.

I am new to GitHub.
Please let me know if I am causing any trouble.

Regards.

2018-07-08 18:00 GMT+09:00 Alexandre Rademaker <notifications@github.com>:

**Comment by jmccrae** [comment]
This looks good to me

**Pull request merged**
