### PR TITLE
Merge Colloquial WordNet in

### LINKED ISSUE #250: Merge synsets from Colloquial WordNet
Tracking issue for merging and checking Colloquial WordNet. Will be formed into a pull request soon.

### PR DESCRIPTION
**Pull request by jmccrae**
Fix #250

### CODE REVIEW

**Comment by 1313ou** [comment]
Synset with id "ewn-90012011-n" and definition "A sexually loose woman"
**has only one member** : LexicalEntry with id "ewn-hoe-n" and Lemma's writtenForm="hoe".

Well... I doubt it's a singleton. Again this is not a dictionary. This is a word net. We should guard against this _whenever-there's-a-new-word-throw-a-synset-at-it_ policy

**Comment by jmccrae** [comment]
Good point, I added some more members to the synset. I don't think this concept exists yet in the wordnet, there is an existing synset but it is not exactly the same:

`ewn-09792353-n` (Interlingual Index: i88094)
(n) loose woman, strumpet, adulteress, trollop, hussy, slut, jade, fornicatress 
> a woman adulterer

**Comment by 1313ou** [comment]
https://wordnet.princeton.edu/documentation/wninput5wn 

- does not define a SIMILAR relation for nouns (it's synset membership)
- does not define a HYPERNYM relation for adjectives
- does not define a HYPERNYM or SIMILAR relation for adverbs

Yet this contrib file has offenders:

```
XPATH /LexicalResource/Lexicon/Synset[@partOfSpeech='n']
Illegal relation pos=n relType=similar id=ewn-90001611-n
Illegal relation pos=n relType=similar id=ewn-90002391-n
Illegal relation pos=n relType=similar id=ewn-90004941-n
Illegal relation pos=n relType=similar id=ewn-90007211-n
Illegal relation pos=n relType=similar id=ewn-90007891-n
Illegal relation pos=n relType=similar id=ewn-91000591-n
Illegal relation pos=n relType=similar id=ewn-91001481-n

XPATH /LexicalResource/Lexicon/Synset[@partOfSpeech='a' or @partOfSpeech='s']
Illegal relation pos=a relType=hypernym id=ewn-90000541-a
Illegal relation pos=a relType=hypernym id=ewn-90000780-a
Illegal relation pos=a relType=hypernym id=ewn-90001041-a
Illegal relation pos=a relType=hypernym id=ewn-90001211-a
Illegal relation pos=a relType=hypernym id=ewn-90001641-a
Illegal relation pos=a relType=hypernym id=ewn-90001811-a
Illegal relation pos=a relType=hypernym id=ewn-90003181-a
Illegal relation pos=a relType=hypernym id=ewn-90005911-a
Illegal relation pos=a relType=hypernym id=ewn-90008781-a
Illegal relation pos=a relType=hypernym id=ewn-90010341-a
Illegal relation pos=a relType=hypernym id=ewn-90010601-a
Illegal relation pos=a relType=hypernym id=ewn-90010621-a
Illegal relation pos=a relType=hypernym id=ewn-90011351-a
Illegal relation pos=a relType=hypernym id=ewn-90013261-a
Illegal relation pos=a relType=hypernym id=ewn-90013262-a
Illegal relation pos=a relType=hypernym id=ewn-90014551-a
Illegal relation pos=a relType=hypernym id=ewn-90016161-a
Illegal relation pos=a relType=hypernym id=ewn-90017941-a
Illegal relation pos=a relType=hypernym id=ewn-90018291-a

XPATH /LexicalResource/Lexicon/Synset[@partOfSpeech='r']
Illegal relation pos=r relType=hypernym id=ewn-90000971-r
Illegal relation pos=r relType=hypernym id=ewn-90000981-r
Illegal relation pos=r relType=similar id=ewn-91000331-r
Illegal relation pos=r relType=similar id=ewn-91001531-r
```

**Comment by jmccrae** [comment]
Similar for nouns was introduced in EuroWordNet (as 'near synonymy'). I think we will introduce more links in the future for similarity between nouns from the results of this project.

Adjective and adverbs are currently a lot less connected than other synsets and the introduction of a hypernym hierarchy would be useful and something this project IMHO should do.

**Comment by 1313ou** [comment]
Ok there are 7 remarkable noun synsets in English that are similar to each other.

**Pull request closed without merging**
