### PR TITLE
Merging adj lexical entries

### PR DESCRIPTION
**Pull request by bbou**
Following issues  #180 and #283 

The adjective lexical entries have been merged and named without adjective position (ewn-aware-p--a + ewn-aware-a -> ewn-aware-a). They group the senses originally split among (otherwise similar) multiple lexentries.

The naming follows the format specification. [see format](https://github.com/globalwordnet/english-wordnet/blob/master/FORMAT.md)

Sense ids **are not affected** and preserve adj position information (ewn-aware-p--a-00191603-01 ewn-aware-a-01984219-02). The order in which they appear is preserved under the new grouping.

**The schema is unchanged** (adj position appears only within the sense id) and has not been exported to an attribute or element. How about provisionally using 'note' or 'dc:type' which are legit ?

Source code
https://github.com/1313ou/ewn-transformation3/blob/master/merge-lexentries3.xsl

This requires a XSLT3.0 transformer and Saxon is used.

Sorry I don't know what pretty-print formatter you use so I left it the way Saxon outputs it.

### CODE REVIEW

**Comment by jmccrae** [comment]
Unfortunately I am going to have to reject this PR as it reformats the source code in a way that would make it hard to track changes.

See [Contribution Guidelines](https://github.com/globalwordnet/english-wordnet/blob/master/CONTRIBUTING.md): "Avoid the use of automatic tools or formatters to keep commits small and trackable."

**Comment by 1313ou** [comment]
Ha!
Will be available  in the fork!!!

Le jeu. 13 févr. 2020 à 12:26, John McCrae <notifications@github.com> a
écrit :

**Comment by jmccrae** [comment]
Hi, so I reformatted this PR to the format. You can see the diff here

https://github.com/globalwordnet/english-wordnet/compare/master..f273f79697301481defb93563d60409e39def994

The diff uncovered a small bug with the lemmas for 'tete-a-tete', 'cock-a-hoop', 'two-a-penny'

A new PR for this is at #287

**Comment by 1313ou** [comment]
-AFAIK there is no pretty-printing policy, or is there ? The data looks like the output of xmllint but it's not, at least with default settings.
-Some of the garbage is due to the DTD (lexicalized = "true"). More on the DTD later.
-The transformer has been fixed to guard against this : [link](https://github.com/1313ou/ewn-transformation3/blob/master/merge-lexentries3.xsl)

**Pull request closed without merging**
